name: mine_sweeper
description: Simple Mine Sweeper game

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  meta: 1.8.0
  freezed_annotation: ^2.2.0
  flutter95: 1.0.0
  go_router: 6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  fonts:
    - family: MineSweeper
      fonts:
        - asset: assets/fonts/mine_sweeper.ttf

